extends:
  - eslint:recommended
  - plugin:react/recommended
env:
  browser: true
  es6: true
plugins:
  - react
rules:
  "react/prop-types": 'off'
  "semi": [2, "always"]
parser: "babel-eslint"
parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
globals:
  App: true
  Promise: true